[package]
name = "lambda_check_db"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
